#include <stdio.h>
#include <rpc/rpc.h>
#include "msg.h"        // generated by rpcgen

/*
 * Remote vrs of printmsg
 */

int * printmessage_1(char **msg, struct svc_req *req)
{
    static int result;
    FILE *fp;

    fp = fopen("/dev/tty", "w");
    if (fp == NULL)
    {
       result = 0;
       return (&result);
    }
    fprintf(fp, "%s\n", *msg);
    fclose(fp);
    result = 1;
    return (&result);
}

